version: "3.8"
networks:
  kinesis.dev.network:
    name: kinesis.dev.network
services:
  localstack:
    container_name: kinesis.dev
    image: localstack/localstack
    ports:
      - "4566-4582:4566-4582"
      - "8080:8080"
    environment:
      - SERVICES=kinesis,dynamodb,cloudwatch
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/home/sim/docker-work/kinesis:/home/kinesis"
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - kinesis.dev.network
